name        : evince
version     : 3.16.1
release     : 10
source      :
    - http://ftp.gnome.org/pub/gnome/sources/evince/3.16/evince-3.16.1.tar.xz : 06ff75065b2a30cd588c402f6bd2ea88ee3166181805e0cc00bd54f71dbf6130
homepage    : https://wiki.gnome.org/Apps/Evince
license     :
    - GPL-2.0
summary     : GNOME Platform Document Viewer
builddeps   :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(cairo-pdf)
    - pkgconfig(cairo-ps)
    - pkgconfig(libsecret-1)
    - pkgconfig(poppler-glib)
    - pkgconfig(adwaita-icon-theme)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libtiff-4)
    - itstool
description : |
    Evince is a document viewer for multiple document formats. The goal of evince is to replace the multiple document viewers that exist on the GNOME Desktop with a single simple application.
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-build-with-Clang.patch
    %configure --disable-browser-plugin \
               --disable-static \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
