name       : evince
version    : 3.24.0
release    : 22
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evince/3.24/evince-3.24.0.tar.xz : 043895af7bbd6f1b57f9ab8778e78cf9c0af5dfcc347eaa94a17bf864c04dc8f
license    : GPL-2.0
component  : office.viewers
summary    : GNOME Platform Document Viewer
description: |
    Evince is a document viewer for multiple document formats. The goal of evince is to replace the multiple document viewers that exist on the GNOME Desktop with a single simple application.
builddeps  :
    - pkgconfig(adwaita-icon-theme)
    - pkgconfig(cairo-pdf)
    - pkgconfig(cairo-ps)
    - pkgconfig(ddjvuapi)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgxps)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-glib)
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-build-with-Clang.patch
    %configure --disable-browser-plugin \
               --disable-static \
               --enable-introspection \
               --enable-djvu
build      : |
    %make
install    : |
    %make_install
