name       : evince
version    : 3.24.1
release    : 26
source     :
    - http://ftp.gnome.org/pub/gnome/sources/evince/3.24/evince-3.24.1.tar.xz : 9ca0c5213407b37be55fddb04a85d9301b692c4412c5920319d975403bff0f37
license    : GPL-2.0
component  : office.viewers
summary    : GNOME Platform Document Viewer
description: |
    Evince is a document viewer for multiple document formats. The goal of evince is to replace the multiple document viewers that exist on the GNOME Desktop with a single simple application.
builddeps  :
    - pkgconfig(adwaita-icon-theme)
    - pkgconfig(cairo-pdf)
    - pkgconfig(cairo-ps)
    - pkgconfig(ddjvuapi)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgxps)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-glib)
    - gtk-doc
    - itstool
    - yelp-tools
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-build-with-Clang.patch
    %reconfigure --disable-browser-plugin \
               --disable-static \
               --enable-djvu \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
