name       : evince
version    : 3.34.2
release    : 36
source     :
    - https://download.gnome.org/sources/evince/3.34/evince-3.34.2.tar.xz : 3cc0955f11204e3a2db1c7ab99b866692749592257485b87304134ad69da0617
license    : GPL-2.0-only
component  : office.viewers
summary    : GNOME Platform Document Viewer
description: |
    Evince is a document viewer for multiple document formats. The goal of evince is to replace the multiple document viewers that exist on the GNOME Desktop with a single simple application.
builddeps  :
    - pkgconfig(adwaita-icon-theme)
    - pkgconfig(cairo-pdf)
    - pkgconfig(cairo-ps)
    - pkgconfig(ddjvuapi)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgxps)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-glib)
    - appstream-glib
    - itstool
    - gnome-common
    - gtk-doc
    - yelp-devel
    - yelp-tools
setup      : |
    %patch -p1 < $pkgfiles/libdocument-Add-transfer-annotation.patch
    %meson_configure -Dps=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
