name       : evince
version    : 3.38.2
release    : 45
source     :
    - https://download.gnome.org/sources/evince/3.38/evince-3.38.2.tar.xz : 27d419d5fed6305e074628edcfde0cb734fffda205d63cac323391c04903bd94
license    : GPL-2.0-only
component  : office.viewers
summary    : GNOME Platform Document Viewer
description: |
    Evince is a document viewer for multiple document formats. The goal of evince is to replace the multiple document viewers that exist on the GNOME Desktop with a single simple application.
builddeps  :
    - pkgconfig(adwaita-icon-theme)
    - pkgconfig(ddjvuapi)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libgxps)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-glib)
    - appstream-glib
    - itstool
setup      : |
    %meson_configure -Dgtk_doc=false -Dps=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
