name       : evince
version    : 3.26.0
release    : 27
source     :
    - https://download.gnome.org/sources/evince/3.26/evince-3.26.0.tar.xz : 79567bdb743cf0c3ed7b638da32afc9b850298f9b4edd532455df4a7e2a4c9d8
license    : GPL-2.0
component  : office.viewers
summary    : GNOME Platform Document Viewer
description: |
    Evince is a document viewer for multiple document formats. The goal of evince is to replace the multiple document viewers that exist on the GNOME Desktop with a single simple application.
builddeps  :
    - pkgconfig(adwaita-icon-theme)
    - pkgconfig(cairo-pdf)
    - pkgconfig(cairo-ps)
    - pkgconfig(ddjvuapi)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgxps)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-glib)
    - gtk-doc
    - itstool
    - yelp-tools
clang      : yes
setup      : |
    %reconfigure --disable-browser-plugin \
               --disable-static \
               --enable-djvu \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
