name       : evince
version    : 3.36.7
release    : 42
source     :
    - https://download.gnome.org/sources/evince/3.36/evince-3.36.7.tar.xz : 65d61a423e3fbbe07001f65e87422dfb7d2e42b9edf0ca6a1d427af9a04b8f32
license    : GPL-2.0-only
component  : office.viewers
summary    : GNOME Platform Document Viewer
description: |
    Evince is a document viewer for multiple document formats. The goal of evince is to replace the multiple document viewers that exist on the GNOME Desktop with a single simple application.
builddeps  :
    - pkgconfig(adwaita-icon-theme)
    - pkgconfig(cairo-pdf)
    - pkgconfig(cairo-ps)
    - pkgconfig(ddjvuapi)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgxps)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-glib)
    - appstream-glib
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/libdocument-Add-transfer-annotation.patch
    %patch -p1 < $pkgfiles/0001-Revert-properties-Update-libnautilus-extension-inclu.patch
    %meson_configure -Dgtk_doc=false -Dps=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
